{"name": "test_network_setup_create_network_invalid_data_type", "status": "passed", "description": "\n        Test network_setup create network failure (invalid data-type)\n        ", "attachments": [{"name": "stdout", "source": "22f1c322-0a42-4afc-bb2f-efae906d50e4-attachment.txt", "type": "text/plain"}], "start": 1661840990116, "stop": 1661840990194, "uuid": "69b072b1-bf38-4dcb-a08d-43dea25a414c", "historyId": "926c42eed7307140a5869a44b4cc9f31", "testCaseId": "7ba48649d0f58a591d8214c7c0311491", "fullName": "tests.shasta_be.test_network.TestNetwork#test_network_setup_create_network_invalid_data_type", "labels": [{"name": "tag", "value": "regression"}, {"name": "parentSuite", "value": "tests.shasta_be"}, {"name": "suite", "value": "test_network"}, {"name": "subSuite", "value": "TestNetwork"}, {"name": "host", "value": "GURM-CGW1JG3"}, {"name": "thread", "value": "795-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.shasta_be.test_network"}]}