{"name": "test_network_setup_create_network_invalid_org_id", "status": "passed", "description": "\n        Test network_setup create network failure (invalid org id)\n        ", "attachments": [{"name": "stdout", "source": "1cba5ea6-8931-47fc-aa74-fdf565947738-attachment.txt", "type": "text/plain"}], "start": 1661840370165, "stop": 1661840370539, "uuid": "f9efe251-c845-4b9b-b807-a7ba8096ae9e", "historyId": "edf3c257a0b8535c34b2234d2e1ef50d", "testCaseId": "59bcff49fa49a5d2716e5aa95263ad72", "fullName": "tests.shasta_be.test_network.TestNetwork#test_network_setup_create_network_invalid_org_id", "labels": [{"name": "tag", "value": "regression"}, {"name": "parentSuite", "value": "tests.shasta_be"}, {"name": "suite", "value": "test_network"}, {"name": "subSuite", "value": "TestNetwork"}, {"name": "host", "value": "GURM-CGW1JG3"}, {"name": "thread", "value": "30535-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.shasta_be.test_network"}]}